name: "user"

on:
  push:
    # run the workflow only on changes
    # to the auth route and auth workflow
    paths:
      - "user/**"
      - ".github/workflows/user.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # run tests for route
      - name: Run ls
        run: |-
          ls
